kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-node-express
  namespace: test
spec:
  ingressClassName: nginx
  rules:
    - host: node-express.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-express
                port:
                  number: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-test
  namespace: test
spec:
  dnsNames:
    - "*.test.dev"
  issuerRef:
    kind: ClusterIssuer
    name: test-issuer
  secretName: test-tls
